---
apiVersion: extensions/v1beta1
#apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: webapp.myexample.com
      http:
        paths:
        - path: /
          backend:
            serviceName: webapp
            servicePort: 80